tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    colors: {
                        "on-primary-container": "#d9c6ff",
                        "surface-variant": "#e2e2e3",
                        "on-tertiary": "#ffffff",
                        "tertiary": "#3e4249",
                        "on-surface-variant": "#4a4456",
                        "outline-variant": "#ccc2d9",
                        "surface": "#f9f9fa",
                        "surface-container": "#eeeeef",
                        "tertiary-fixed": "#dfe2ec",
                        "on-tertiary-fixed": "#181c23",
                        "surface-tint": "#741bf8",
                        "tertiary-container": "#555961",
                        "surface-dim": "#d9dadb",
                        "on-secondary-fixed": "#191b24",
                        "on-primary-fixed-variant": "#5900c7",
                        "surface-bright": "#f9f9fa",
                        "secondary": "#5c5e68",
                        "inverse-surface": "#2f3132",
                        "on-error-container": "#93000a",
                        "on-secondary-fixed-variant": "#444650",
                        "error-container": "#ffdad6",
                        "tertiary-fixed-dim": "#c3c6d0",
                        "outline": "#7b7488",
                        "secondary-fixed-dim": "#c5c6d2",
                        "surface-container-highest": "#e2e2e3",
                        "on-primary": "#ffffff",
                        "secondary-fixed": "#e1e1ee",
                        "surface-container-low": "#f3f3f4",
                        "on-tertiary-container": "#cdd0d9",
                        "primary-fixed": "#eaddff",
                        "surface-container-lowest": "#ffffff",
                        "background": "#f9f9fa",
                        "secondary-container": "#e1e1ee",
                        "on-surface": "#1a1c1d",
                        "primary-container": "#6e06f2",
                        "error": "#ba1a1a",
                        "primary": "#5200b9",
                        "inverse-primary": "#d2bcff",
                        "on-secondary-container": "#62646e",
                        "on-tertiary-fixed-variant": "#43474f",
                        "on-error": "#ffffff",
                        "primary-fixed-dim": "#d2bcff",
                        "on-primary-fixed": "#24005a",
                        "inverse-on-surface": "#f0f1f2",
                        "surface-container-high": "#e8e8e9",
                        "on-background": "#1a1c1d",
                        "on-secondary": "#ffffff"
                    },
                    fontFamily: {
                        "headline": ["Plus Jakarta Sans"],
                        "body": ["Inter"],
                        "label": ["Inter"]
                    },
                    borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
                },
            },
        }
